### ISSUE TITLE
Panic crash 

### ISSUE THREAD

**Issue by dmccallie** [pocketbase/pocketbase#1468]
I'm not sure if this is the right place to leave a bug report. I'm running PB version 0.10.4 under WSL2 (Ubuntu 20.04.4) and I got the following crash right after adding a new collection via the admin UX.  Prior to the crash PB had been working fine. I only have 4 collections, and only small amounts of test data in use.

> panic: SyntaxError: SyntaxError: (anonymous): Line 3:17 Unexpected token : (and 1 more errors)
> 
> goroutine 1 [running]:
> github.com/pocketbase/pocketbase/plugins/jsvm.MustRegisterMigrations(...)
>         /home/runner/work/pocketbase/pocketbase/plugins/jsvm/migrations.go:39
> main.main()
>         /home/runner/work/pocketbase/pocketbase/examples/base/main.go:62 +0x39d

Any suggestions on what might have caused this?

--david

**Comment by ganigeorgiev** [comment]
Hm, it is possible that some of the generated migration templates are not properly generated. Could you check your migration files in `pb_migrations` and post them here?

**Comment by dmccallie** [comment]
Indeed - when I hid the pb_migrations directory, everything started normally.
Here is the most recently created migration file (xxx_created_images.js)

```
> migrate((db) => {
  const collection = new Collection({
    "id": "m9509ss6nd1cj35",
    "created": "2023-01-02 03:01:44.560Z",
    "updated": "2023-01-02 03:01:44.560Z",
    "name": "images",
    "type": "base",
    "system": false,
    "schema": [
      {
        "system": false,
        "id": "1jno1xf4",
        "name": "image",
        "type": "file",
        "required": false,
        "unique": false,
        "options": {
          "maxSelect": 1,
          "maxSize": 5242880,
          "mimeTypes": [
            "image/jpg",
            "image/jpeg",
            "image/png",
            "image/svg+xml",
            "image/gif"
          ],
          "thumbs": []
        }
      },
      {
        "system": false,
        "id": "jwzfczqa",
        "name": "filename",
        "type": "text",
        "required": false,
        "unique": false,
        "options": {
          "min": null,
          "max": null,
          "pattern": ""
        }
      }
    ],
    "listRule": null,
    "viewRule": null,
    "createRule": null,
    "updateRule": null,
    "deleteRule": null,
    "options": {}
  });

  return Dao(db).saveCollection(collection);
}, (db) => {
  const dao = new Dao(db);
  const collection = dao.findCollectionByNameOrId("m9509ss6nd1cj35");

  return dao.deleteCollection(collection);
})
```
And here is the full xxx_collections_snapshot.js

```
> migrate((db) => {
  const snapshot = [
    {
      "id": "_pb_users_auth_",
      "created": "2022-12-19 23:53:26.095Z",
      "updated": "2022-12-20 02:21:30.417Z",
      "name": "users",
      "type": "auth",
      "system": false,
      "schema": [
        {
          "system": false,
          "id": "users_name",
          "name": "name",
          "type": "text",
          "required": false,
          "unique": false,
          "options": {
            "min": null,
            "max": null,
            "pattern": ""
          }
        },
        {
          "system": false,
          "id": "users_avatar",
          "name": "avatar",
          "type": "file",
          "required": false,
          "unique": false,
          "options": {
            "maxSelect": 1,
            "maxSize": 5242880,
            "mimeTypes": [
              "image/jpg",
              "image/jpeg",
              "image/png",
              "image/svg+xml",
              "image/gif"
            ],
            "thumbs": null
          }
        }
      ],
      "listRule": "id = @request.auth.id",
      "viewRule": "id = @request.auth.id",
      "createRule": "",
      "updateRule": "",
      "deleteRule": "",
      "options": {
        "allowEmailAuth": true,
        "allowOAuth2Auth": true,
        "allowUsernameAuth": true,
        "exceptEmailDomains": null,
        "manageRule": null,
        "minPasswordLength": 8,
        "onlyEmailDomains": null,
        "requireEmail": false
      }
    },
    {
      "id": "25u8xbw8jo8w2po",
      "created": "2022-12-20 00:32:14.022Z",
      "updated": "2022-12-22 07:09:45.389Z",
      "name": "projects",
      "type": "base",
      "system": false,
      "schema": [
        {
          "system": false,
          "id": "6q3kwsew",
          "name": "name",
          "type": "text",
          "required": true,
          "unique": false,
          "options": {
            "min": 2,
            "max": 64,
            "pattern": ""
          }
        },
        {
          "system": false,
          "id": "arhd9hoi",
          "name": "tagline",
          "type": "text",
          "required": true,
          "unique": false,
          "options": {
            "min": 2,
            "max": 64,
            "pattern": ""
          }
        },
        {
          "system": false,
          "id": "ysyzqgxv",
          "name": "description",
          "type": "text",
          "required": false,
          "unique": false,
          "options": {
            "min": 2,
            "max": 512,
            "pattern": ""
          }
        },
        {
          "system": false,
          "id": "d9q4nmfo",
          "name": "url",
          "type": "text",
          "required": true,
          "unique": false,
          "options": {
            "min": 2,
            "max": 128,
            "pattern": ""
          }
        },
        {
          "system": false,
          "id": "5j2efhb3",
          "name": "thumbnail",
          "type": "file",
          "required": false,
          "unique": false,
          "options": {
            "maxSelect": 1,
            "maxSize": 5242880,
            "mimeTypes": [
              "image/jpg",
              "image/jpeg",
              "image/png",
              "image/svg+xml",
              "image/gif",
              "image/webp"
            ],
            "thumbs": [
              "80x80"
            ]
          }
        },
        {
          "system": false,
          "id": "yu87ucds",
          "name": "user",
          "type": "relation",
          "required": true,
          "unique": false,
          "options": {
            "maxSelect": 1,
            "collectionId": "_pb_users_auth_",
            "cascadeDelete": true
          }
        }
      ],
      "listRule": "@request.auth.id != \"\"",
      "viewRule": "",
      "createRule": "@request.auth.id != \"\" && @request.auth.id = @request.data.user",
      "updateRule": "",
      "deleteRule": "",
      "options": {}
    },
    {
      "id": "esdrob0od1zrjso",
      "created": "2022-12-22 02:28:39.812Z",
      "updated": "2022-12-22 02:33:42.077Z",
      "name": "blogs",
      "type": "base",
      "system": false,
      "schema": [
        {
          "system": false,
          "id": "dpxlxqke",
          "name": "title",
          "type": "text",
          "required": true,
          "unique": false,
          "options": {
            "min": null,
            "max": null,
            "pattern": ""
          }
        },
        {
          "system": false,
          "id": "mfbozzpo",
          "name": "author",
          "type": "text",
          "required": false,
          "unique": false,
          "options": {
            "min": null,
            "max": null,
            "pattern": ""
          }
        },
        {
          "system": false,
          "id": "5dndoihv",
          "name": "description",
          "type": "text",
          "required": false,
          "unique": false,
          "options": {
            "min": null,
            "max": 300,
            "pattern": ""
          }
        },
        {
          "system": false,
          "id": "adiatniw",
          "name": "content",
          "type": "text",
          "required": true,
          "unique": false,
          "options": {
            "min": null,
            "max": null,
            "pattern": ""
          }
        },
        {
          "system": false,
          "id": "wmzuc77p",
          "name": "entered_by",
          "type": "relation",
          "required": true,
          "unique": false,
          "options": {
            "maxSelect": 1,
            "collectionId": "_pb_users_auth_",
            "cascadeDelete": false
          }
        },
        {
          "system": false,
          "id": "bozjm9qm",
          "name": "featured_image",
          "type": "file",
          "required": false,
          "unique": false,
          "options": {
            "maxSelect": 1,
            "maxSize": 5242880,
            "mimeTypes": [],
            "thumbs": []
          }
        },
        {
          "system": false,
          "id": "omwidzka",
          "name": "published",
          "type": "bool",
          "required": true,
          "unique": false,
          "options": {}
        }
      ],
      "listRule": "",
      "viewRule": "",
      "createRule": "",
      "updateRule": "",
      "deleteRule": "",
      "options": {}
    }
  ];

  const collections = snapshot.map((item) => new Collection(item));

  return Dao(db).importCollections(collections, true, null);
}, (db) => {
  return null;
})

```

Thanks for the quick reply!!
--david

**Comment by ganigeorgiev** [comment]
@dmccallie Both migrations are working fine for me.

Are there other migrations? Could you post them all here or check them for invalid js?

**Comment by dmccallie** [comment]
Do all migration files end in ".js" ? I don't see any other JS files in the pb_migrations directory. There are none in the top-level directory, though there is a JSON file there from a schema export I did a few days ago.  Where else should I look?

--david

**Comment by ganigeorgiev** [comment]
> There are none in the top-level directory, though there is a JSON file there from a schema export I did a few days ago. 

Ah, The JSON file is the reason for the error since we are parsing all root level `pb_migration` files as js files.

Move the `.json` file to another directory and it should start normally. I'll consider in future version to add a check to skip non `.js` files.

**Comment by dmccallie** [comment]
I appear to be up and running fine, so thank you!

However, I can reproduce the original panic failure message in a second clean directory that has only the pocketbase executable and the` pb_migrations` directory containing the two files that I pasted earlier.  No pb_data and no JSON files. 

There is also a `pocketbase:Zone.Identifier` file in the directory, which I assume is irrelevant, but I note that under windows explorer, the colon in the` pocketbase:Zone.Identifier` string is reported as a non-ascii character??

I'd be happy to zip it all up and send it to you, or we can just move on since it's now working!

--david

**Comment by ganigeorgiev** [comment]
Any non-valid js file will cause an error (_the collections json actually should be fine as long as it is properly formatted since it is a valid JS array_).

In this case, I suspect the culprit is `pocketbase:Zone.Identifier`.
This is not PocketBase maintained file and it is most likely created by Windows, WSL2 or your IDE. Remove it and try again.

**Comment by dmccallie** [comment]
Thanks again. Apparently Windows has been putting those files in a hidden mode under Windows, but when copying a file over to WSL, they show up. How annoying.

However, the crash still occurs even when the Zone..Identifier file is removed.  :(

Please know that I am not complaining, but I thought you should know that something may still be funky.  Maybe one of my pb_migrations JS files has been subtly corrupted, since you can't reproduce with the cut-paste of the same data. Regardless, I'm happy to move on!

--david

**Comment by ganigeorgiev** [comment]
I can't think of other reason why "Unexpected token:..." error will be thrown. Either Windows create some hidden files inside the `pb_migrations` or, as you noted, it is possible that the content of your js file is corrupted somehow.

In any case, in the upcoming v0.11.0 (sometime later this week) I'll improve the error reporting so that it can show which file is failing and will add a filter to load only the `.js` files from the `pb_migrations`.

**Comment by dmccallie** [comment]
Oops - I mislead you. I said I had deleted the Zone-Identifier file but I had deleted the wrong one! When I removed the ZI file that was _inside_ the pb_migrations directory, the problem went away.  Problem solved.
