### ISSUE TITLE
ReferenceError: EventSource is not defined

### ISSUE THREAD

**Issue by LeCyreaxYT** [pocketbase/pocketbase#1606]
Hey, I want to make an external Backend Server with Node.js and Express to handle extra Stuff Like Payments and co.

All working but when i try to use subscribe i get this error because EventSource is only in Browser available.

```
[1] ReferenceError: EventSource is not defined
[1]     at RealtimeService.initConnect (file:///C:/Users/alecs/Desktop/RescueOS/RescueOS_Backend/node_modules/pocketbase/dist/pocketbase.es.mjs:1:35103)
[1]     at file:///C:/Users/alecs/Desktop/RescueOS/RescueOS_Backend/node_modules/pocketbase/dist/pocketbase.es.mjs:1:34799
[1]     at new Promise (<anonymous>)
[1]     at RealtimeService.<anonymous> (file:///C:/Users/alecs/Desktop/RescueOS/RescueOS_Backend/node_modules/pocketbase/dist/pocketbase.es.mjs:1:34697)
[1]     at step (file:///C:/Users/alecs/Desktop/RescueOS/RescueOS_Backend/node_modules/pocketbase/dist/pocketbase.es.mjs:1:2088)
[1]     at Object.next (file:///C:/Users/alecs/Desktop/RescueOS/RescueOS_Backend/node_modules/pocketbase/dist/pocketbase.es.mjs:1:2193)
[1]     at file:///C:/Users/alecs/Desktop/RescueOS/RescueOS_Backend/node_modules/pocketbase/dist/pocketbase.es.mjs:1:1103
[1]     at new Promise (<anonymous>)
[1]     at __awaiter (file:///C:/Users/alecs/Desktop/RescueOS/RescueOS_Backend/node_modules/pocketbase/dist/pocketbase.es.mjs:1:789)
[1]     at RealtimeService.connect (file:///C:/Users/alecs/Desktop/RescueOS/RescueOS_Backend/node_modules/pocketbase/dist/pocketbase.es.mjs:1:34569)
```

Is there a way to use subscribe or currently not?

**Comment by ganigeorgiev** [comment]
@chinochao Node doesn't have a native `EventSource` implementation and you'll have to load a polyfill. For example:

```js
// npm install eventsource --save
import eventsource from 'eventsource';

global.EventSource = eventsource;

...
```

This and other caveats you can find in the JS SDK readme - https://github.com/pocketbase/js-sdk#nodejs-via-npm.
