### ISSUE TITLE
failed fetch on pocketbase with nextjs 13

### ISSUE THREAD

**Issue by ChangJoo-Park** [pocketbase/pocketbase#1820]
Sometimes I failed fetch list query pocketbase with nextjs 13 :(

It happens when I call twice at once

```log
error - node_modules/pocketbase/dist/pocketbase.es.mjs (1:2273) @ new ClientResponseError
error - ClientResponseError 0: Something went wrong while processing your request.
    at new ClientResponseError (webpack-internal:///(api)/./node_modules/pocketbase/dist/pocketbase.es.mjs:17:2285)
    at eval (webpack-internal:///(api)/./node_modules/pocketbase/dist/pocketbase.es.mjs:17:40471)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async handler (webpack-internal:///(api)/./pages/api/product.ts:12:18)
    at async Object.apiResolver (/Users/changjoopark/experiments/exp_cosmetics/node_modules/next/dist/server/api-utils/node.js:372:9)
    at async DevServer.runApi (/Users/changjoopark/experiments/exp_cosmetics/node_modules/next/dist/server/next-server.js:488:9)
    at async Object.fn (/Users/changjoopark/experiments/exp_cosmetics/node_modules/next/dist/server/next-server.js:751:37)
    at async Router.execute (/Users/changjoopark/experiments/exp_cosmetics/node_modules/next/dist/server/router.js:253:36)
    at async DevServer.run (/Users/changjoopark/experiments/exp_cosmetics/node_modules/next/dist/server/base-server.js:384:29)
    at async DevServer.run (/Users/changjoopark/experiments/exp_cosmetics/node_modules/next/dist/server/dev/next-dev-server.js:743:20)
    at async DevServer.handleRequest (/Users/changjoopark/experiments/exp_cosmetics/node_modules/next/dist/server/base-server.js:322:20) {
  url: '',
  status: 0,
  data: {},
  isAbort: false,
  originalError: DOMException [AbortError]: This operation was aborted
      at Object.fetch (/Users/changjoopark/experiments/exp_cosmetics/node_modules/next/dist/compiled/undici/index.js:1:26686)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async handler (webpack-internal:///(api)/./pages/api/product.ts:12:18)
      at async Object.apiResolver (/Users/changjoopark/experiments/exp_cosmetics/node_modules/next/dist/server/api-utils/node.js:372:9)
      at async DevServer.runApi (/Users/changjoopark/experiments/exp_cosmetics/node_modules/next/dist/server/next-server.js:488:9)
      at async Object.fn (/Users/changjoopark/experiments/exp_cosmetics/node_modules/next/dist/server/next-server.js:751:37)
      at async Router.execute (/Users/changjoopark/experiments/exp_cosmetics/node_modules/next/dist/server/router.js:253:36)
      at async DevServer.run (/Users/changjoopark/experiments/exp_cosmetics/node_modules/next/dist/server/base-server.js:384:29)
      at async DevServer.run (/Users/changjoopark/experiments/exp_cosmetics/node_modules/next/dist/server/dev/next-dev-server.js:743:20)
      at async DevServer.handleRequest (/Users/changjoopark/experiments/exp_cosmetics/node_modules/next/dist/server/base-server.js:322:20),
  page: '/api/product'
}
null
event - compiled client and server successfully in 403 ms (624 modules)
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at parseModel (/Users/changjoopark/experiments/exp_cosmetics/node_modules/next/dist/compiled/react-server-dom-webpack/client.js:40:15)
    at initializeModelChunk (/Users/changjoopark/experiments/exp_cosmetics/node_modules/next/dist/compiled/react-server-dom-webpack/client.js:400:18)
    at resolveModelChunk (/Users/changjoopark/experiments/exp_cosmetics/node_modules/next/dist/compiled/react-server-dom-webpack/client.js:366:5)
    at resolveModel (/Users/changjoopark/experiments/exp_cosmetics/node_modules/next/dist/compiled/react-server-dom-webpack/client.js:635:5)
    at processFullRow (/Users/changjoopark/experiments/exp_cosmetics/node_modules/next/dist/compiled/react-server-dom-webpack/client.js:729:9)
    at processBinaryChunk (/Users/changjoopark/experiments/exp_cosmetics/node_modules/next/dist/compiled/react-server-dom-webpack/client.js:789:5)
    at progress (/Users/changjoopark/experiments/exp_cosmetics/node_modules/next/dist/compiled/react-server-dom-webpack/client.js:842:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by ganigeorgiev** [comment]
Without a code sample, I'm not sure what could be the cause of the issue.

The above error indicates that the request was aborted and I suspect that this is because of the JS SDK autocancellation - https://github.com/pocketbase/js-sdk#auto-cancellation, aka. you are making multiple similar requests without awaiting the previous ones to complete (this usually indicates async bugs in user-land code, but if you want disable the autocancellation completely, you can set `pb.autoCancellation(false)`).

If that's not the case, please provide more details (or minimal reproducible repo) and I'll investigate it further.

**Comment by ChangJoo-Park** [comment]
Sorry @ganigeorgiev , with your guides,`autoCancellation`, it completely solived
