### ISSUE TITLE
fatal error: concurrent map writes

### ISSUE THREAD

**Issue by iMro0t** [pocketbase/pocketbase#2272]
```
fatal error: concurrent map writes

goroutine 443 [running]:
github.com/pocketbase/pocketbase/tools/list.ExistInSliceWithRegex({0xc0de370910, 0x10}, {0xc00069f7a0?, 0x6, 0x102f2f4c0?})
        /Users/****/go/pkg/mod/github.com/pocketbase/pocketbase@v0.13.4/tools/list/list.go:67 +0x1cd
github.com/pocketbase/pocketbase/resolvers.(*runner).run(0xc0de313e80)
        /Users/****/go/pkg/mod/github.com/pocketbase/pocketbase@v0.13.4/resolvers/record_field_resolve_runner.go:50 +0x89
github.com/pocketbase/pocketbase/resolvers.parseAndRun(...)
        /Users/****/go/pkg/mod/github.com/pocketbase/pocketbase@v0.13.4/resolvers/record_field_resolve_runner.go:25
github.com/pocketbase/pocketbase/resolvers.(*RecordFieldResolver).Resolve(0xc00027a460, {0xc0de370910, 0x10})
        /Users/****/go/pkg/mod/github.com/pocketbase/pocketbase@v0.13.4/resolvers/record_field_resolver.go:142 +0x78
github.com/pocketbase/pocketbase/tools/search.resolveToken({{0x1015997e5?, 0x28?}, {0xc0de370910?, 0xc0000ca060?}}, {0x102362810?, 0xc00027a460?})
...
```

https://github.com/pocketbase/pocketbase/blob/b7407edcae15c469f00ef3caf6e6da6cf0d30876/tools/list/list.go#L42-L76

Possible Solution: use `sync.Mutex`

**Comment by ganigeorgiev** [comment]
I'm not able to reproduce it. Could you elaborate a little more when the panic happen? Do you have custom code that could trigger it?

**Comment by ganigeorgiev** [comment]
Ok, I see why this could happen. I'll try to submit a fix sometime later today.

**Comment by ganigeorgiev** [comment]
Should be fixed in https://github.com/pocketbase/pocketbase/releases/tag/v0.14.4.

_The internal cache will be optimized in the near future and probably replaced with LRU style cache._
