### ISSUE TITLE
Pocketbase panic: ReferenceError: global is not defined at node_modules/process/index.js:2:18(2)

### ISSUE THREAD

**Issue by DjMeska** [pocketbase/pocketbase#2292]
Related to https://github.com/pocketbase/pocketbase/discussions/2125
Repro repo: https://github.com/DjMeska/PocketbaseIssue
Pocketbase has some dependency conflict with node.js modules.
```
panic: ReferenceError: global is not defined at node_modules/process/index.js:2:18(2)

goroutine 1 [running]:
github.com/dop251/goja_nodejs/require.Require(0xc0002e87e0?, {0x2041af7, 0x7})
        /home/runner/go/pkg/mod/github.com/dop251/goja_nodejs@v0.0.0-20221009164102-3aa5028e57f6/require/module.go:205 +0x125       
github.com/dop251/goja_nodejs/process.Enable(0xc0002fdd00?)
        /home/runner/go/pkg/mod/github.com/dop251/goja_nodejs@v0.0.0-20221009164102-3aa5028e57f6/process/module.go:30 +0x2a
github.com/pocketbase/pocketbase/plugins/jsvm.RegisterMigrations({0x2e2d280?, 0xc0002fdc00?}, 0x1?)
        /home/runner/work/pocketbase/pocketbase/plugins/jsvm/migrations.go:73 +0x252
github.com/pocketbase/pocketbase/plugins/jsvm.MustRegisterMigrations(...)
        /home/runner/work/pocketbase/pocketbase/plugins/jsvm/migrations.go:40
main.main()
        /home/runner/work/pocketbase/pocketbase/examples/base/main.go:71 +0x285
```
Potential workarounds: 
1. Wrap pocketbase files to a folder. Which helped for few times but not anymore.
2. You can delete pb_migrations folder and it will run normally, but well I need that data so yea....

pb_migrations folder currently has 1 file
1681059633_updated_users.js
```
migrate((db) => {
  const dao = new Dao(db)
  const collection = dao.findCollectionByNameOrId("_pb_users_auth_")

  // remove
  collection.schema.removeField("users_avatar")

  // add
  collection.schema.addField(new SchemaField({
    "system": false,
    "id": "xkiujlam",
    "name": "admin",
    "type": "bool",
    "required": false,
    "unique": false,
    "options": {}
  }))

  return dao.saveCollection(collection)
}, (db) => {
  const dao = new Dao(db)
  const collection = dao.findCollectionByNameOrId("_pb_users_auth_")

  // add
  collection.schema.addField(new SchemaField({
    "system": false,
    "id": "users_avatar",
    "name": "avatar",
    "type": "file",
    "required": false,
    "unique": false,
    "options": {
      "maxSelect": 1,
      "maxSize": 5242880,
      "mimeTypes": [
        "image/jpeg",
        "image/png",
        "image/svg+xml",
        "image/gif",
        "image/webp"
      ],
      "thumbs": null
    }
  }))

  // remove
  collection.schema.removeField("xkiujlam")

  return dao.saveCollection(collection)
})
```
Thought it might have something to do with global npm packages, but couldn't find any leads besides maybe yarn?
Global npm packages folder
![image](https://user-images.githubusercontent.com/47053730/231990996-5d33d8fe-9206-45be-b26a-d25c2f8750aa.png)

Also here is my package.json if anyone tries to repro it.
```
{
  "name": "pvp",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "start": "env-cmd -f ./env/.env craco start",
    "build": "env-cmd -f ./env/.env.production craco build",
    "test": "craco test",
    "format": "prettier --write src/**/*.ts{,x}",
    "lint": "tsc --noEmit && eslint src/**/*.ts{,x}",
    "eject": "react-scripts eject"
  },
  "engines": {
    "node": "16.13.0"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "dependencies": {
    "@chakra-ui/react": "^1.7.4",
    "@emotion/react": "11",
    "@emotion/styled": "11",
    "aos": "^2.3.4",
    "axios": "^1.3.4",
    "chakra-react-select": "^4.1.4",
    "framer-motion": "^4.1.17",
    "moment": "^2.29.4",
    "pocketbase": "^0.13.1",
    "react": "^17.0.1",
    "react-blockies": "^1.4.1",
    "react-dom": "^17.0.1",
    "react-router-dom": "^5.2.0",
    "react-scripts": "4.0.3",
    "typescript": "^4.1.2"
  },
  "devDependencies": {
    "@craco/craco": "^6.1.1",
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "@types/jest": "^26.0.15",
    "@types/node": "^12.0.0",
    "@types/react": "^17.0.0",
    "@types/react-blockies": "^1.4.1",
    "@types/react-dom": "^17.0.0",
    "@types/react-router-dom": "^5.2.0",
    "@typescript-eslint/eslint-plugin": "^4.17.0",
    "@typescript-eslint/parser": "^4.17.0",
    "env-cmd": "^10.1.0",
    "eslint": "^7.2.0",
    "eslint-config-airbnb": "18.2.1",
    "eslint-config-airbnb-typescript": "^12.3.1",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-jest": "^24.2.1",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-react": "^7.21.5",
    "eslint-plugin-react-hooks": "^1.7.0",
    "prettier": "^2.2.1"
  },
  "resolutions": {
    "react-error-overlay": "6.0.9"
  }
}
```
In pocketbase data there is only 1 user created and that's it.

**Comment by DjMeska** [comment]
The issue persists for me in this repo.
Created repo
https://github.com/DjMeska/PocketbaseIssue
@ganigeorgiev

**Comment by ganigeorgiev** [comment]
@DjMeska I was able to reproduce it with the provided package.json and could confirm that it is the same as in https://github.com/pocketbase/pocketbase/discussions/2125.

Moving the PocketBase executable in its own folder works for me. I've tried with the following dir structure:

```
myapp/
  - package.json
  - node_modules/
  - pb/
    - pocketbase
    - pb_data/
    - pb_migrations/
```

Note that `node_modules` resolution is affected by the current working directory, meaning that:

```
# this will fail
$ cd myapp
$ ./pb/pocketbase serve

# but this will work
$ cd myapp/pb
$ ./pocketbase serve
```

The best workaround for now would be to keep the PocketBase files out of your frontend folder to avoid CWD conflicts, aka. have a structure like:

```
myapp/
  - frontend/
    ...
  - pb/
    ...
```

As mentioned in https://github.com/pocketbase/pocketbase/discussions/2125#discussioncomment-5391721, eventually in the future we may specify an explicit `node_modules` resolution strategy, but that will be handled together with the planned [JS app hooks](https://github.com/orgs/pocketbase/projects/2?pane=issue&itemId=17629907) since the jsvm registration will have to change anyway.

**Comment by DjMeska** [comment]
Oh yes you are correct
i was running pocketbase from root folder without setting cd
```
./pb/pocketbase serve
```
NGL its kinda weird issue that you cant run it out of root

**Comment by ganigeorgiev** [comment]
> NGL its kinda weird issue that you cant run it out of root

You can, it is just dependent on the working directory (CWD).
