### ISSUE TITLE
Only admins can perform this action error even though I am admin

### ISSUE THREAD

**Issue by serkan-bayram** [pocketbase/pocketbase#3903]
Code: 

```js 

export async function voteEmoji(ratingId, emoji) {
  console.log("on the server");

  const pb = await authAsAdmin();

  console.log("am I admin: ", pb.authStore.isAdmin);

  const { session } = await getSession();

  const userId = session.user.record.id;

  const data = {
    ratingId: ratingId,
    userId: userId,
    emoji: emoji,
  };

  try {
    const record = await pb.collection("emojis").create(data);
    revalidatePath("/oyla");
    return { message: true };
  } catch (error) {
    console.log("Error:", error);
  }

  return { message: false };
}

```

Error: 

on the server
am I admin:  true
Error: ClientResponseError 403: Only admins can perform this action.
    at eval (webpack-internal:///(action-browser)/./node_modules/pocketbase/dist/pocketbase.es.mjs:1069:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async voteEmoji (webpack-internal:///(action-browser)/./app/oyla/components/voteEmoji.jsx:27:24)
    at async /home/serkan/programming/yemekhane-puanla/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.dev.js:36:6051
    at async tM (/home/serkan/programming/yemekhane-puanla/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.dev.js:36:4746)
    at async Z (/home/serkan/programming/yemekhane-puanla/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.dev.js:36:30238)
    at async doRender (/home/serkan/programming/yemekhane-puanla/node_modules/next/dist/server/base-server.js:1294:26)
    at async cacheEntry.responseCache.get.incrementalCache.incrementalCache (/home/serkan/programming/yemekhane-puanla/node_modules/next/dist/server/base-server.js:1446:28)
    at async /home/serkan/programming/yemekhane-puanla/node_modules/next/dist/server/response-cache/index.js:102:36 {
  url: 'http://myip/api/collections/emojis/records',
  status: 403,
  response: {
    code: 403,
    message: 'Only admins can perform this action.',
    data: {}
  },
  isAbort: false,
  originalError: {
    url: 'http://myip/api/collections/emojis/records',
    status: 403,
    data: {
      code: 403,
      message: 'Only admins can perform this action.',
      data: {}
    }
  }
}

**Comment by ganigeorgiev** [comment]
It shouldn't have any effect as we don't have cache by default.

In any case note that the above password authentication function could be slow if executed every time due to the bcrypt hash verification.

A better approach for admin authentication is to have a single server global admin instance that you can just import in your server-side actions. For example:

```
// src/adminClient.js
import PocketBase from "pocketbase"

const adminClient = new PocketBase(process.env.dbURL);

// the credentials can be filled via env variables
await pb.admins.authWithPassword(process.env.dbUsername, process.env.dbPassword, {
  // This will trigger auto refresh or auto reauthentication in case
  // the token has expired or is going to expire in the next 30 minutes.
  autoRefreshThreshold: 30 * 60
})

export default adminClient;
```

And then in your serverside actions you can just import it and use it directly:

```js
import adminClient from "src/adminClient.js";

export async function voteEmoji(ratingId, emoji) {
    ...

    await adminClient.collection("emojis").create(data);

    ...
}

```

**Comment by serkan-bayram** [comment]
Hi, I was trying to implement your suggestion on authAsAdmin but I have an issue, in your code you wrote it as "await adminClient...", but you are not in an async function, how is "await" going to work? When I try to use your code, it throws an error: " SyntaxError: await is only valid in async functions and the top level bodies of modules". I tried it without the "await" but it throws a couple errors at the begining and it fixes a bit later, which is not good. Do you have an idea?

**Comment by ganigeorgiev** [comment]
From the [MDN docs]():

> It can only be used inside an [async function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function) or **at the top level of a [module](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules)**.

Or in other words make sure that you are using ESM (eg. your `package.json` has `"type":"module"`).

In any case, please if you have further questions use the Q&A discussions.

**Comment by danditomaso** [comment]
I was running into this issue as well, and after digging around. I realized by default all collections are locked to admin access only, which is why you are most likely getting this error. Take a look at this article and apply rules per collection that will allow your users to create/update records as required. https://pocketbase.io/docs/api-rules-and-filters/

**Comment by ppenter** [comment]
> Thanks, pb.authStore.isValid returned false. so I added cache: no-store option and it works now. I don't know is it the best practice tho.
> 
> ```js
> export async function authAsAdmin() {
>   const pb = new PocketBase(process.env.dbURL);
> 
>   await pb.admins.authWithPassword(
>     process.env.dbUsername,
>     process.env.dbPassword,
>     { cache: "no-store" }
>   );
> 
>   return pb;
> }
> ```

I don't know why, but this is the solution. In my scenario, I deploy it using vercel it should add no-cache but in localhost (pnpm run start) it can run perfectly without no-cache.

**Comment by developerasun** [comment]
try to reauthenticate again if status code is 403 and your codes seems okay. 

I think I read pocketbase login token session is one-hour long in pocketbase document somewhere.

So each request validating token expiration will solve this access control problem like

```ts
const validateTokenSession = ( ) => {
  const pb = new PocketBase(process.env.dbURL);

  const authData = await pb.admins.authWithPassword(
    process.env.dbUsername,
    process.env.dbPassword,
  );

const { token }= authData
const { authStore: { isValid }  } = token

logger.debug("is pb token valid?: ", isValid)

if (!isValid) {
// login again
await pb.admins.authWithPassword(
    process.env.dbUsername,
    process.env.dbPassword,
  );
}
}
```

hope it helps!
