### ISSUE TITLE
Saving settings in a pre-bootstrap onBootstrap hook fails

### ISSUE THREAD

**Issue by hibatos** [pocketbase/pocketbase#6020]
It seems that $app.save in the hooks logic does not work as intended when fed a settings object in an onBootstrap hook if event.next is not called first (works in onBootstrap **after** bootstrap but **not before** bootstrap).

This code works:
```js
onBootstrap((e) => {
    e.next(); //<-
    const settings = $app.settings();
    settings.smtp.tls = true;
    $app.save(settings);
})
```

This does not:
```js
onBootstrap((e) => {
    const settings = $app.settings();
    settings.smtp.tls = true;
    $app.save(settings);
    e.next(); //<-
})
```

The error that gets dumped into the console:

```shell
database$ ./pocketbase serve
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x88 pc=0x112c602]

goroutine 1 [running]:
github.com/dop251/goja.(*Runtime).RunProgram.func1()
        /home/runner/go/pkg/mod/github.com/dop251/goja@v0.0.0-20241009100908-5f46f2705ca3/runtime.go:1450 +0x28d
panic({0x162b8c0?, 0x2ba0230?})
        /opt/hostedtoolcache/go/1.23.3/x64/src/runtime/panic.go:785 +0x132
github.com/dop251/goja.(*vm).handleThrow(0xc000562240, {0x162b8c0, 0x2ba0230})
        /home/runner/go/pkg/mod/github.com/dop251/goja@v0.0.0-20241009100908-5f46f2705ca3/vm.go:834 +0x405
github.com/dop251/goja.(*vm).runTryInner.func1()
        /home/runner/go/pkg/mod/github.com/dop251/goja@v0.0.0-20241009100908-5f46f2705ca3/vm.go:876 +0x3f
panic({0x162b8c0?, 0x2ba0230?})
        /opt/hostedtoolcache/go/1.23.3/x64/src/runtime/panic.go:785 +0x132
github.com/dop251/goja.(*vm).handleThrow(0xc000562240, {0x162b8c0, 0x2ba0230})
        /home/runner/go/pkg/mod/github.com/dop251/goja@v0.0.0-20241009100908-5f46f2705ca3/vm.go:834 +0x405
github.com/dop251/goja.(*vm).runTryInner.func1()
        /home/runner/go/pkg/mod/github.com/dop251/goja@v0.0.0-20241009100908-5f46f2705ca3/vm.go:876 +0x3f
panic({0x162b8c0?, 0x2ba0230?})
        /opt/hostedtoolcache/go/1.23.3/x64/src/runtime/panic.go:785 +0x132
github.com/dop251/goja.(*vm).handleThrow(0xc000562240, {0x162b8c0, 0x2ba0230})
        /home/runner/go/pkg/mod/github.com/dop251/goja@v0.0.0-20241009100908-5f46f2705ca3/vm.go:834 +0x405
github.com/dop251/goja.(*vm).runTryInner.func1()
        /home/runner/go/pkg/mod/github.com/dop251/goja@v0.0.0-20241009100908-5f46f2705ca3/vm.go:876 +0x3f
panic({0x162b8c0?, 0x2ba0230?})
        /opt/hostedtoolcache/go/1.23.3/x64/src/runtime/panic.go:785 +0x132
github.com/pocketbase/pocketbase/core.(*BaseApp).create.func1.1.1(0x46ac5d?)
        /home/runner/work/pocketbase/pocketbase/core/db.go:315 +0x1a2
github.com/pocketbase/pocketbase/core.baseLockRetry(0xc000863a90, 0xc)
        /home/runner/work/pocketbase/pocketbase/core/db_retry.go:47 +0x48
github.com/pocketbase/pocketbase/core.(*BaseApp).create.func1.1(0xc0004e6af0)
        /home/runner/work/pocketbase/pocketbase/core/db.go:299 +0x73
github.com/pocketbase/pocketbase/tools/hook.(*Hook[...]).Trigger.func1()
        /home/runner/work/pocketbase/pocketbase/tools/hook/hook.go:169 +0x5e
github.com/pocketbase/pocketbase/tools/hook.(*Event).Next(...)
        /home/runner/work/pocketbase/pocketbase/tools/hook/event.go:32
github.com/pocketbase/pocketbase/core.(*BaseApp).registerRecordHooks.func3(0xc0004e6af0)
        /home/runner/work/pocketbase/pocketbase/core/record_model.go:94 +0x3c
github.com/pocketbase/pocketbase/tools/hook.(*TaggedHook[...]).Bind.func1()
        /home/runner/work/pocketbase/pocketbase/tools/hook/tagged.go:63 +0x62
github.com/pocketbase/pocketbase/tools/hook.(*Hook[...]).Trigger.func1()
        /home/runner/work/pocketbase/pocketbase/tools/hook/hook.go:169 +0x5e
github.com/pocketbase/pocketbase/tools/hook.(*Event).Next(...)
        /home/runner/work/pocketbase/pocketbase/tools/hook/event.go:32
github.com/pocketbase/pocketbase/core.(*BaseApp).registerCollectionHooks.func3(0xc0004e6af0)
        /home/runner/work/pocketbase/pocketbase/core/collection_model.go:72 +0x102
github.com/pocketbase/pocketbase/tools/hook.(*TaggedHook[...]).Bind.func1()
        /home/runner/work/pocketbase/pocketbase/tools/hook/tagged.go:63 +0x62
github.com/pocketbase/pocketbase/tools/hook.(*Hook[...]).Trigger.func1()
        /home/runner/work/pocketbase/pocketbase/tools/hook/hook.go:169 +0x5e
github.com/pocketbase/pocketbase/tools/hook.(*Event).Next(...)
        /home/runner/work/pocketbase/pocketbase/tools/hook/event.go:32
github.com/pocketbase/pocketbase/tools/hook.(*Hook[...]).Trigger(0x1f39dc0, 0xc0004e6af0, {0xc000863de8, 0x1, 0x177a6c0})
        /home/runner/work/pocketbase/pocketbase/tools/hook/hook.go:173 +0x3c2
github.com/pocketbase/pocketbase/core.(*BaseApp).create.func1(0xc0004e6af0?)
        /home/runner/work/pocketbase/pocketbase/core/db.go:291 +0xcd
github.com/pocketbase/pocketbase/tools/hook.(*Hook[...]).Trigger.func1()
        /home/runner/work/pocketbase/pocketbase/tools/hook/hook.go:169 +0x5e
github.com/pocketbase/pocketbase/tools/hook.(*Event).Next(...)
        /home/runner/work/pocketbase/pocketbase/tools/hook/event.go:32
github.com/pocketbase/pocketbase/core.(*BaseApp).registerRecordHooks.func2(0xc0004e6af0)
        /home/runner/work/pocketbase/pocketbase/core/record_model.go:79 +0x3c
github.com/pocketbase/pocketbase/tools/hook.(*TaggedHook[...]).Bind.func1()
        /home/runner/work/pocketbase/pocketbase/tools/hook/tagged.go:63 +0x62
github.com/pocketbase/pocketbase/tools/hook.(*Hook[...]).Trigger.func1()
        /home/runner/work/pocketbase/pocketbase/tools/hook/hook.go:169 +0x5e
github.com/pocketbase/pocketbase/tools/hook.(*Event).Next(...)
        /home/runner/work/pocketbase/pocketbase/tools/hook/event.go:32
github.com/pocketbase/pocketbase/core.(*BaseApp).registerCollectionHooks.func2(0xc0004e6af0)
        /home/runner/work/pocketbase/pocketbase/core/collection_model.go:57 +0x102
github.com/pocketbase/pocketbase/tools/hook.(*TaggedHook[...]).Bind.func1()
        /home/runner/work/pocketbase/pocketbase/tools/hook/tagged.go:63 +0x62
github.com/pocketbase/pocketbase/tools/hook.(*Hook[...]).Trigger.func1()
        /home/runner/work/pocketbase/pocketbase/tools/hook/hook.go:169 +0x5e
github.com/pocketbase/pocketbase/tools/hook.(*Event).Next(...)
        /home/runner/work/pocketbase/pocketbase/tools/hook/event.go:32
github.com/pocketbase/pocketbase/tools/hook.(*Hook[...]).Trigger(0x1f39dc0, 0xc0004e6af0, {0xc0008641c0, 0x1, 0x4})
        /home/runner/work/pocketbase/pocketbase/tools/hook/hook.go:173 +0x3c2
github.com/pocketbase/pocketbase/core.(*BaseApp).create(0xc00047b888, {0x1f2a9a8, 0x2c17000}, {0x1f2e390, 0xc0001d2908}, 0x1, 0x0)
        /home/runner/work/pocketbase/pocketbase/core/db.go:281 +0x1b4
github.com/pocketbase/pocketbase/core.(*BaseApp).save(0xc00047b888, {0x1f2a9a8, 0x2c17000}, {0x1f2e390, 0xc0001d2908}, 0x1, 0x0)
        /home/runner/work/pocketbase/pocketbase/core/db.go:268 +0x6e
github.com/pocketbase/pocketbase/core.(*BaseApp).SaveWithContext(...)
        /home/runner/work/pocketbase/pocketbase/core/db.go:187
github.com/pocketbase/pocketbase/core.(*BaseApp).Save(0x1?, {0x1f2e390?, 0xc0001d2908?})
        /home/runner/work/pocketbase/pocketbase/core/db.go:180 +0x3a
reflect.Value.call({0x17f1bc0?, 0xc00047b888?, 0xc000864848?}, {0x17f7af7, 0x4}, {0xc00076af48, 0x1, 0xc00008a648?})
        /opt/hostedtoolcache/go/1.23.3/x64/src/reflect/value.go:581 +0xca6
reflect.Value.Call({0x17f1bc0?, 0xc00047b888?, 0xc000867e90?}, {0xc00076af48?, 0xc000621520?, 0x2?})
        /opt/hostedtoolcache/go/1.23.3/x64/src/reflect/value.go:365 +0xb9
github.com/dop251/goja.(*Runtime).newWrappedFunc.(*Runtime).wrapReflectFunc.func1({{0x1f37ad8, 0xc0008676e0}, {0xc000627910, 0x1, 0xf}})
        /home/runner/go/pkg/mod/github.com/dop251/goja@v0.0.0-20241009100908-5f46f2705ca3/runtime.go:2020 +0x3bd
github.com/dop251/goja.(*nativeFuncObject).vmCall(0xc00085a9c0, 0xc000562240, 0x1)
        /home/runner/go/pkg/mod/github.com/dop251/goja@v0.0.0-20241009100908-5f46f2705ca3/func.go:563 +0x184
github.com/dop251/goja.call.exec(0x4?, 0xc000562240)
        /home/runner/go/pkg/mod/github.com/dop251/goja@v0.0.0-20241009100908-5f46f2705ca3/vm.go:3629 +0x66
github.com/dop251/goja.(*vm).run(0xc000562240)
        /home/runner/go/pkg/mod/github.com/dop251/goja@v0.0.0-20241009100908-5f46f2705ca3/vm.go:628 +0x5b
github.com/dop251/goja.(*vm).runTryInner(0xc000562240?)
        /home/runner/go/pkg/mod/github.com/dop251/goja@v0.0.0-20241009100908-5f46f2705ca3/vm.go:880 +0x52
github.com/dop251/goja.(*baseJsFuncObject).__call(0xc0006b16c0, {0xc0002772a0?, 0x1, 0xc000560a50?}, {0x0, 0x0}, {0x0?, 0x0?})
        /home/runner/go/pkg/mod/github.com/dop251/goja@v0.0.0-20241009100908-5f46f2705ca3/func.go:426 +0x711
github.com/dop251/goja.(*baseJsFuncObject)._call(...)
        /home/runner/go/pkg/mod/github.com/dop251/goja@v0.0.0-20241009100908-5f46f2705ca3/func.go:442
github.com/dop251/goja.(*arrowFuncObject).Call(0xc00011d950?, {{0x1f37f00, 0x2c17000}, {0xc0002772a0, 0x1, 0x6}})
        /home/runner/go/pkg/mod/github.com/dop251/goja@v0.0.0-20241009100908-5f46f2705ca3/func.go:386 +0x51
github.com/dop251/goja.(*Runtime).functionproto_call(0x1f37ad8?, {{0x1f37ad8, 0xc000867bc0}, {0xc000277290, 0x2, 0x7}})
        /home/runner/go/pkg/mod/github.com/dop251/goja@v0.0.0-20241009100908-5f46f2705ca3/builtin_function.go:111 +0x114
github.com/dop251/goja.(*nativeFuncObject).vmCall(0xc000a0ed20, 0xc000562240, 0x2)
        /home/runner/go/pkg/mod/github.com/dop251/goja@v0.0.0-20241009100908-5f46f2705ca3/func.go:563 +0x184
github.com/dop251/goja.call.exec(0x9?, 0xc000562240)
        /home/runner/go/pkg/mod/github.com/dop251/goja@v0.0.0-20241009100908-5f46f2705ca3/vm.go:3629 +0x66
github.com/dop251/goja.(*vm).run(0xc000562240)
        /home/runner/go/pkg/mod/github.com/dop251/goja@v0.0.0-20241009100908-5f46f2705ca3/vm.go:628 +0x5b
github.com/dop251/goja.(*vm).runTryInner(0xc000562240?)
        /home/runner/go/pkg/mod/github.com/dop251/goja@v0.0.0-20241009100908-5f46f2705ca3/vm.go:880 +0x52
github.com/dop251/goja.(*baseJsFuncObject).__call(0xc00085a780, {0xc00038b1e0?, 0x1, 0x410685?}, {0x0, 0x0}, {0x1f37f00?, 0x2c17000?})
        /home/runner/go/pkg/mod/github.com/dop251/goja@v0.0.0-20241009100908-5f46f2705ca3/func.go:426 +0x711
github.com/dop251/goja.(*baseJsFuncObject)._call(...)
        /home/runner/go/pkg/mod/github.com/dop251/goja@v0.0.0-20241009100908-5f46f2705ca3/func.go:442
github.com/dop251/goja.(*baseJsFuncObject).call(0x0?, {{0x1f37f00, 0x2c17000}, {0xc00038b1e0, 0x1, 0x1}}, {0x0?, 0x0?})
        /home/runner/go/pkg/mod/github.com/dop251/goja@v0.0.0-20241009100908-5f46f2705ca3/func.go:450 +0x76
github.com/dop251/goja.(*baseJsFuncObject).Call(...)
        /home/runner/go/pkg/mod/github.com/dop251/goja@v0.0.0-20241009100908-5f46f2705ca3/func.go:382
github.com/dop251/goja.(*Runtime).functionproto_apply(0xc0004d0c08?, {{0x1f37ad8, 0xc000867440}, {0xc00068b8a0, 0x2, 0x6}})
        /home/runner/go/pkg/mod/github.com/dop251/goja@v0.0.0-20241009100908-5f46f2705ca3/builtin_function.go:98 +0x123
github.com/dop251/goja.(*nativeFuncObject).vmCall(0xc000a0ebe0, 0xc000562240, 0x2)
        /home/runner/go/pkg/mod/github.com/dop251/goja@v0.0.0-20241009100908-5f46f2705ca3/func.go:563 +0x184
github.com/dop251/goja.call.exec(0x6?, 0xc000562240)
        /home/runner/go/pkg/mod/github.com/dop251/goja@v0.0.0-20241009100908-5f46f2705ca3/vm.go:3629 +0x66
github.com/dop251/goja.(*vm).run(0xc000562240)
        /home/runner/go/pkg/mod/github.com/dop251/goja@v0.0.0-20241009100908-5f46f2705ca3/vm.go:628 +0x5b
github.com/dop251/goja.(*vm).runTryInner(0x50?)
        /home/runner/go/pkg/mod/github.com/dop251/goja@v0.0.0-20241009100908-5f46f2705ca3/vm.go:880 +0x52
github.com/dop251/goja.(*vm).runTry(0xc000562240)
        /home/runner/go/pkg/mod/github.com/dop251/goja@v0.0.0-20241009100908-5f46f2705ca3/vm.go:866 +0x1e5
github.com/dop251/goja.(*Runtime).RunProgram(0xc0004d0c08, 0xc000857950)
        /home/runner/go/pkg/mod/github.com/dop251/goja@v0.0.0-20241009100908-5f46f2705ca3/runtime.go:1472 +0x43c
github.com/pocketbase/pocketbase/plugins/jsvm.hooksBinds.func1.1.1(0xc0004d0c08)
        /home/runner/work/pocketbase/pocketbase/plugins/jsvm/binds.go:81 +0xb7
github.com/pocketbase/pocketbase/plugins/jsvm.(*vmsPool).run(0xc00023c0c0, 0xc000865630)
        /home/runner/work/pocketbase/pocketbase/plugins/jsvm/pool.go:65 +0x194
github.com/pocketbase/pocketbase/plugins/jsvm.hooksBinds.func1.1({0xc000a10e28, 0x1, 0x1?})
        /home/runner/work/pocketbase/pocketbase/plugins/jsvm/binds.go:78 +0x14d
github.com/pocketbase/pocketbase/tools/hook.(*Hook[...]).Trigger.func1()
        /home/runner/work/pocketbase/pocketbase/tools/hook/hook.go:169 +0x5e
github.com/pocketbase/pocketbase/tools/hook.(*Event).Next(...)
        /home/runner/work/pocketbase/pocketbase/tools/hook/event.go:32
github.com/pocketbase/pocketbase/plugins/jsvm.Register.func1(0x7fbf154ca378?)
        /home/runner/work/pocketbase/pocketbase/plugins/jsvm/jsvm.go:131 +0x31
github.com/pocketbase/pocketbase/tools/hook.(*Hook[...]).Trigger.func1()
        /home/runner/work/pocketbase/pocketbase/tools/hook/hook.go:169 +0x5e
github.com/pocketbase/pocketbase/tools/hook.(*Event).Next(...)
        /home/runner/work/pocketbase/pocketbase/tools/hook/event.go:32
github.com/pocketbase/pocketbase/core.(*BaseApp).registerAutobackupHooks.func2(0x0?)
        /home/runner/work/pocketbase/pocketbase/core/base_backup.go:332 +0x2e
github.com/pocketbase/pocketbase/tools/hook.(*Hook[...]).Trigger.func1()
        /home/runner/work/pocketbase/pocketbase/tools/hook/hook.go:169 +0x5e
github.com/pocketbase/pocketbase/tools/hook.(*Event).Next(...)
        /home/runner/work/pocketbase/pocketbase/tools/hook/event.go:32
github.com/pocketbase/pocketbase/tools/hook.(*Hook[...]).Trigger(0x1f3a600, 0xc000a10df8, {0xc000865d50, 0x1, 0xc00003e070})
        /home/runner/work/pocketbase/pocketbase/tools/hook/hook.go:173 +0x3c2
github.com/pocketbase/pocketbase/core.(*BaseApp).Bootstrap(0xc00047b888)
        /home/runner/work/pocketbase/pocketbase/core/base.go:382 +0xfc
github.com/pocketbase/pocketbase.(*PocketBase).Execute(0xc00051eb40)
        /home/runner/work/pocketbase/pocketbase/pocketbase.go:160 +0x36
github.com/pocketbase/pocketbase.(*PocketBase).Start(0xc00051eb40)
        /home/runner/work/pocketbase/pocketbase/pocketbase.go:150 +0x88
main.main()
        /home/runner/work/pocketbase/pocketbase/examples/base/main.go:119 +0x5c5
```

Is that intended behaviour or is this a bug?
Thanks in advance

**Comment by ganigeorgiev** [comment]
It is working correctly. The database, migrations, app settings, etc. are initialized only after the Bootstrap has been executed, aka. after `e.next()`. This is currenly mentioned in the godocs (e.g. https://pkg.go.dev/github.com/pocketbase/pocketbase#New) but I'll consider adding a more explicit note in the hooks documentation too.
